/// Référentiel magasin : pays, région, surface, statut.
table DimStore
	lineageTag: b5afa69d-606b-45df-922d-94f9d3bf39b9

	column StoreKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: df97b372-de61-4100-bf59-2cbf3749bb1d
		summarizeBy: none
		sourceColumn: StoreKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StoreCode
		dataType: string
		lineageTag: 97d9ef96-6910-4aac-b158-9aa1724453a1
		summarizeBy: none
		sourceColumn: StoreCode

		annotation SummarizationSetBy = Automatic

	column GeoAreaKey
		dataType: int64
		formatString: 0
		lineageTag: 49c53eab-5325-4f9b-b09a-517161895059
		summarizeBy: count
		sourceColumn: GeoAreaKey

		annotation SummarizationSetBy = Automatic

	column CountryCode
		dataType: string
		lineageTag: be50755e-2e73-4e6e-bae0-0edb25c73b06
		summarizeBy: none
		sourceColumn: CountryCode

		annotation SummarizationSetBy = Automatic

	column CountryName
		dataType: string
		lineageTag: ee6053dc-c0c7-484f-817d-01227c753762
		summarizeBy: none
		sourceColumn: CountryName

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 45d7df40-1631-49fc-9450-10c17571d073
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column OpenDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 20466974-81d5-4be8-9970-0c1c845a296a
		summarizeBy: none
		sourceColumn: OpenDate

		variation Variation
			isDefault
			relationship: d7f884d1-ba00-4b36-9d76-d3db0ef9f4e9
			defaultHierarchy: LocalDateTable_4cd3fb52-ed78-41e6-b5b5-5961c98fd129.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CloseDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 54baf958-e9db-4dc1-b9a4-562170321beb
		summarizeBy: none
		sourceColumn: CloseDate

		variation Variation
			isDefault
			relationship: 3bd005f0-d243-456f-8e94-849765a84414
			defaultHierarchy: LocalDateTable_86dd263f-a3ec-4d59-80bc-ba6d875d9ae6.'Hiérarchie de dates'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Description
		dataType: string
		lineageTag: 12920946-9f38-4a17-ae1a-a7148d280f11
		summarizeBy: none
		sourceColumn: Description

		annotation SummarizationSetBy = Automatic

	column SquareMeters
		dataType: int64
		formatString: 0
		lineageTag: 69560c90-1e8e-4aa4-9351-bae908079bd4
		summarizeBy: sum
		sourceColumn: SquareMeters

		annotation SummarizationSetBy = Automatic

	column Status
		dataType: string
		lineageTag: 9eec5336-9004-41cc-bc0a-80cb7eff8c00
		summarizeBy: none
		sourceColumn: Status

		annotation SummarizationSetBy = Automatic

	partition DimStore = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\main data\Abed work\PowerBI\NordRetail\Data\store.csv"),[Delimiter=",", Columns=11, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"StoreKey", Int64.Type}, {"StoreCode", type text}, {"GeoAreaKey", Int64.Type}, {"CountryCode", type text}, {"CountryName", type text}, {"State", type text}, {"OpenDate", type date}, {"CloseDate", type date}, {"Description", type text}, {"SquareMeters", Int64.Type}, {"Status", type text}})
				in
				    #"Type modifié"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

