/// Snapshot mensuel des stocks. Grain : produit × magasin × mois.
table FactInventory
	lineageTag: 69ae5e44-9241-41f4-9962-f377cda6f325

	measure 'Stock Level' =
			
			--niveau de stock total
			SUM(FactInventory[StockLevel])
		formatString: 0
		displayFolder: 04- Operations
		lineageTag: cee7b91d-8a5c-425f-9bba-847f0cd7d21b

	measure 'Days of Stock' =
			
			-- jours de couverture moyens
			AVERAGE(FactInventory[DaysOfStock])
		displayFolder: 04- Operations
		lineageTag: 3d3d6913-cdc5-4c87-9b91-ce03a058e636

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Out of Stock Products' =
			
			--produits en rupture
			CALCULATE(
			    DISTINCTCOUNT(FactInventory[ProductKey]),
			    FactInventory[StockLevel] = 0
			)
		formatString: 0
		displayFolder: 04- Operations
		lineageTag: 65989de8-194a-4e00-8503-ef3aadac0835

	measure 'Stock Coverage Alert' = IF([Days of Stock] < 7, "Alert", "OK")
		lineageTag: 2f76ecbd-b183-403c-a247-4f667772eacb

	column ProductKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 69a8bdca-395e-4702-a6f8-3b0692aacb78
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StoreKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a145b319-601f-47a1-997a-05068abcdd9f
		summarizeBy: none
		sourceColumn: StoreKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 8f85d201-6441-435f-af07-edd1752b97cc
		summarizeBy: none
		sourceColumn: DateKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column StockLevel
		dataType: int64
		formatString: 0
		lineageTag: 3b9b0e72-60ec-4bb5-803c-b3015452750e
		summarizeBy: sum
		sourceColumn: StockLevel

		annotation SummarizationSetBy = Automatic

	column ReorderThreshold
		dataType: int64
		formatString: 0
		lineageTag: c72328c5-c1e1-4c2f-9325-2aa911af73f6
		summarizeBy: sum
		sourceColumn: ReorderThreshold

		annotation SummarizationSetBy = Automatic

	column DaysOfStock
		dataType: double
		lineageTag: 79d10789-5179-4a33-9637-32e2a8f3ce84
		summarizeBy: sum
		sourceColumn: DaysOfStock

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition FactInventory = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\main data\Abed work\PowerBI\NordRetail\Data\inventory.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"ProductKey", Int64.Type}, {"StoreKey", Int64.Type}, {"DateKey", Int64.Type}, {"StockLevel", Int64.Type}, {"ReorderThreshold", Int64.Type}, {"DaysOfStock", type text}}),
				    #"Type modifié avec paramètres régionaux" = Table.TransformColumnTypes(#"Type modifié", {{"DaysOfStock", type number}}, "en-US")
				in
				    #"Type modifié avec paramètres régionaux"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

